.github folder
mu-box/.github pull request #1
Opened 2019-09-07 20:47 UTC by niden

Created .github repo for common issue templates and funding
Added stale.yml for the stale bot

2019-09-08 06:24 UTC, danhunsaker commented
Any particular reason to move the files into a subdir? They work as well in the root... Is there another use for this repo that you had in mind?

2019-09-08 13:43 UTC, niden commented
@danhunsaker I was just following what we did in phalcon. so the fiiles that we had in .gitignore I put them in .gitignore.

Not sure if it works when you have them all in the root. If it does I will re-move them.

2019-09-08 14:37 UTC, niden commented
@danhunsaker I checked the docs. The files do not need to be in their own `.github` folder so I moved them all to the root.

2019-09-10 17:54 UTC, danhunsaker requested changes
Left some thoughts inline.

2019-09-10 17:54 UTC, danhunsaker commented on ISSUE_TEMPLATE.md
> +```php
Probably want to remove highlighting on this one...

2019-09-10 17:54 UTC, danhunsaker commented on ISSUE_TEMPLATE.md
> +```php
...and switch this one to `bash`...

2019-09-10 17:54 UTC, danhunsaker commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] I have read and understood the [Contributing Guidelines](https://github.com/mu-box/core/blob/master/CONTRIBUTING.md)
We don't actually have one of these... Can we add one to this PR?

2019-09-10 17:54 UTC, danhunsaker commented on stale.yml
> +  Thank you for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way an
May want to drop the "read more at" bit, since we're not Phalcon?

2019-09-10 17:54 UTC, danhunsaker commented on stale.yml
> +#  Thank you for contributing to this issue. As it has been 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way a
Same here, even though it's commented.

2019-09-10 18:10 UTC, niden commented
@danhunsaker updated

2019-09-10 23:18 UTC, danhunsaker requested changes
A couple of typos, then this is good to go!

2019-09-10 23:18 UTC, danhunsaker commented on CONTRIBUTING.md
> +* Come join the Microbos [Discord](https://discord.gg/MCDdHfy)
Typo!

2019-09-10 23:18 UTC, danhunsaker commented on CONTRIBUTING.md
> +* Please ensure that information such as OS and Microbox versionare part of the bug report
Lost a space in here...

2019-09-11 00:10 UTC, niden commented
@danhunsaker Fixed

2019-09-11 00:20 UTC, danhunsaker approved these changes

2019-09-11 00:20 UTC, merged

2019-09-11 00:21 UTC, danhunsaker commented
Thanks!